#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_aws_cloudwatch_agent="0.0.1"
  jq -n --arg aws_cloudwatch_agent "$ver_aws_cloudwatch_agent" '{aws_cloudwatch_agent: $aws_cloudwatch_agent}'
}

version "$@"
